name: chla-pod1
services:
    mariadb-chla:
        container_name: mariadb-chla
        image: registry.redhat.io/rhel9/mariadb-1011:latest  #DevMode only
        labels:
            - description:"Database for demo"
        restart: always #DevMode only
        volumes: #DevMode only
            - /local/data/DB/Chla_DB: /var/lib/mysql/data:Z
        command: [ "sh", "/home/toto/bin/app",  "--config", "/mnt/config/env.conf" ] #DevMode only
        ports:
            - MARIADB_PORT: 3306
        environment:
            - MYSQL_USER=usertoto
            - MYSQL_PASSWORD="totopwd"
            - MYSQL_DATABASE="devel-db"
        secrets:
            - mariadb-chla-secret
        configs:
            - jhkjhkjhjh
            - yyy
        working_dir: /var/lib/mysql/data
        deploy: #DevMode only
            resources:
                limits:
                    cpus: 1
                    memory: 256M
                reservations:
                    cpus: '1'
                    memory: 128M
