name: chla-pod1
services:
    mariadb-chhhhla:
        container_name: mariadb-chla
        image: registry.redhat.io/rhel9/mariadb-1011:latest
        labels:
            - description:"Database for demo"
        restart: always
        volumes:
            - /local/data/DB/Chla_DB: /var/lib/mysql/data
        ports:
            - 14306: 3306
        environment:
            - MYSQL_USER=chlauser
            - MYSQL_PASSWORD=chlauser1
        secrets:
            - mariadb-chla-secret
        security_opt:
            - "label=level:s0:c100,c101"
        configs:
            - jhkjhkjhjh
            - yyy
        working_dir: /var/lib/mysql/data
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 512M
                reservations:
                    cpus: '1.5'
                    memory: 256M
