variables:
    HOST_NAME:          "127.0.0.1"
    LOCALIP:            "___LOCALIP___"
    SERVICENAME:        "NOTSET"
    MARIADB_PORT:       "14306"
    REDIS_PORT:         "6379"
    OTELGRPC_PORT:      "4317"
    OTELHTTP_PORT:      "4318"
    MARIADB_USER:       "chlauser"
    MARIADB_PASSWORD:   "chlauser1"
    MARIADB_DATABASE:   "chladb"
    JAEGERPROTO_PORT:   "14250"
    JAEGERTHRIFT_PORT:  "14268"
    JAEGERADMIN_PORT:   "14269"
    JAEGERGRPC_PORT:    "4317"
    JAEGERHTTP_PORT:    "4318"
    JAEGERCONFIG_PORT:  "5778"
    #JAEGERZIPKIN_PORT: "9411"
    JAEGERGUI_PORT:     "16686"
    ENVOY_ADM_PORT:     "9901"
    ENVOY_HTTP_PORT:    "8082"
    ENVOY_GRPC_PORT:    "8083"
    LABELC100:          "c100"
    LABELC110:          "c110"
    LABELC120:          "c120"
genericoutput: #  Options added to all containers
    labels:
        - comment= "Chla Configuration"
    #environment:
        #- PODMAN_USERNS="keep-id:uid=1000,gid=1000"
networks:
    chla1_network:
      description: Network 1 for CHLA
      subnet: 10.87.0.0/24
      gateway: 10.87.0.1
    chla2_network:
      description: Network 1 for CHLA
      subnet: 10.88.0.0/24
      gateway: 10.88.0.1
pods:
    chla-pod1:
      description: Chla Pod1
      networks:
        - chla1_network
    chla-pod2:
      description: Chla Pod2
      networks:
        - chla2_network
services:
    mariadb-chla:
        image: registry.redhat.io/rhel9/mariadb-1011:latest
        volumes:
            - /local/data/DB/Chla_DB: /var/lib/mysql/data
        ports:
            - MARIADB_PORT:3306
    redis-db:
        labels:
            - copyright: "CHLA28 property 2025"
        image: docker.io/redislabs/redis
        volumes:
            - /local/data/DB/redis_data: /data
        ports:
            - REDIS_PORT:6379
    jaeger:
        labels:
            - metrics: "false"
        #image: docker.io/jaegertracing/all-in-one:1.60
        image: registry.redhat.io/rhosdt/jaeger-all-in-one-rhel8:latest
        ports:
            #- JAEGERPROTO_PORT: 14250
            #- JAEGERTHRIFT_PORT: 14268
            - JAEGERADMIN_PORT: 14269
            - JAEGERGRPC_PORT: 4317
            - JAEGERHTTP_PORT: 4318
            #- JAEGERCONFIG_PORT: 5778
            #- JAEGERZIPKIN_PORT: 9411
            - JAEGERGUI_PORT: 16686
#metrics:
#    environment:
#        - JAVA_TOOL_OPTIONS=-javaagent:/mnt/opentelemetry-javaagent.jar
#        - OTEL_SERVICE_NAME=$SERVICENAME
#        - OTEL_RESOURCE_ATTRIBUTES=service=$SERVICENAME,env=dev
#        - OTEL_EXPORTER_OTLP_ENDPOINT=http://$LOCALIP:$OTELGRPC_PORT
#        - OTEL_METRIC_EXPORT_INTERVAL=15000
#        - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
#        - OTEL_LOGS_EXPORTER=otlp
#        - OTEL_TRACES_EXPORTER=otlp
#        - OTEL_METRICS_EXPORTER=otlp
#metricshttp:
#    environment:
#        - JAVA_TOOL_OPTIONS=-javaagent:/mnt/opentelemetry-javaagent.jar
#        - OTEL_SERVICE_NAME=$SERVICENAME
#        - OTEL_RESOURCE_ATTRIBUTES=service=$SERVICENAME,env=dev
#        - OTEL_EXPORTER_OTLP_ENDPOINT=http://$LOCALIP:$OTELHTTP_PORT
#        - OTEL_METRIC_EXPORT_INTERVAL=15000
#        - OTEL_LOGS_EXPORTER=otlp
#        - OTEL_TRACES_EXPORTER=otlp
#        - OTEL_METRICS_EXPORTER=otlp
