name: compose2target
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0-70.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  checked_yaml: ^2.0.3
  json_annotation: ^4.9.0
  http: ^1.2.2
  path: ^1.9.1
  process_run: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
