name: chla-pod1
services:
    mariadb-chla:
        container_name: mariadb-chla
        image: registry.redhat.io/rhel9/mariadb-1011:latest  #DevMode only
        labels:
            - description:"Database for demo"
        annotations:
            # will generate in pcs command: op start timeout=30s start-delay=30s
            - c2t.ha.start="timeout=30s start-delay=30s"
            # will generate in pcs command: op monitor interval=40s timeout=60s start-delay=40s
            #- c2t.ha.monitor="interval=40s timeout=60s start-delay=40s"
            - c2t.ha.monitor='interval="40s" timeout="60s" start-delay="40s"'
            # will generate in pcs command: op stop timeout=60s
            - c2t.ha.stop="timeout=60s"
            # monitor_cmd parameter with pcs command
            - c2t.ha.monitorcmd="/mnt/checkStatus.sh"
            - c2t.ha.meta='target-role="Started"'
        restart: always #DevMode only
        volumes: #DevMode only
            - /local/data/DB/Chla_DB: /var/lib/mysql/data:Z
        command: [ "sh", "/home/toto/bin/app",  "--config", "/mnt/config/env.conf" ] #DevMode only
        ports:
            - MARIADB_PORT: 3306
        secrets:
            - mariadb-chla-secret
        #configs:
        #    - jhkjhkjhjh
        #    - yyy
        working_dir: /var/lib/mysql/data
        deploy: #DevMode only
            resources:
                limits:
                    cpus: 1
                    memory: 256M
                reservations:
                    cpus: '1'
                    memory: 128M
